# This file contains the data used to build the members grid. It is built
# following the TOML file format (https://toml.io/en/).
#
# Please start every new member with a [[members]] heading, and include
# a name, the path to their logo (these are located in the /staticmembers/founding_members
# directory), and the information that is shown in the overlay when visitors
# click on the logo.
#
# Please note that the logos must have a transparency layer set (implying
# that they should be saved as PNG or WebP images) for the hover effects
# to work. A white background alone will not result in a pleasing effect.

[[members]]
name = "Deutsche Gesellschaft für Psychologie"
url = "https://www.dgps.de/"
logo = "members/founding_members/dgps.png"

  [[members.contacts]]
  name = "Prof. Dr. Christian Fiebach"
  url = "https://www.dgps.de/index.php?id=christianfiebach"


[[members]]
name = "Helmholtz Association"
url = "https://www.helmholtz.de/"
logo = "members/founding_members/helmholtz.png"

  [[members.contacts]]
  name = "Dr. Bernadette Fritzsch"
  url = "https://os.helmholtz.de/"

  [[members.contacts]]
  name = "Antonia Schrader"
  url = "https://os.helmholtz.de/"

[[members]]
name = "Helmholtz Artificial Intelligence Cooperation Unit"
url = "https://www.helmholtz.ai/"
logo = "members/founding_members/helmholtz-ai.png"

  [[members.contacts]]
  name = "Dr. Heidi Seibold"
  url = "https://www.helmholtz.ai/themenmenue/our-research/research-groups/seibolds-group/index.html"


[[members]]
name = "Leibniz Information Centre for Economics"
url = "https://www.zbw.eu/en/"
logo = "members/founding_members/zbw.svg"

  [[members.contacts]]
  name = "Prof. Dr. Klaus Tochtermann"
  url = "http://www.zbw.eu/de/forschung/klaus-tochtermann/"


[[members]]
name = "Open Science Center at LMU Munich"
url = "https://www.osc.uni-muenchen.de"
logo = "members/founding_members/lmu-osc.png"

  [[members.contacts]]
  name = "Prof. Dr. Felix Schönbrodt"
  url = "https://www.osc.uni-muenchen.de/members/individual-members/schoenbrodt/index.html"


[[members]]
name = "Network of Open Science Initiatives"
logo = "members/founding_members/nosi.png"

  [[members.contacts]]
  name = "Dr. Susann Fiedler"
  url = "https://www.coll.mpg.de/susann-fiedler"

  [[members.contacts]]
  name = "Dr. Rima-Maria Rahal"
  url = "https://www.coll.mpg.de/135848/dr-rima-maria-rahal"


[[members]]
name = "Quest Center"
url = "https://www.bihealth.org/de/forschung/quest-center"
logo = "members/founding_members/quest.svg"

  [[members.contacts]]
  name = "Prof. Dr. Ulrich Dirnagl"
  url = "https://www.bihealth.org/de/forschung/quest-center/team/quest-office/"

[[members]]
name = "Berlin University Alliance"
url = "https://www.berlin-university-alliance.de/"
logo = "members/founding_members/bua.png"
subtitle = "Funded under the Excellence Strategy of the Federal Government and the Länder by the Berlin University Alliance"

  [[members.contacts]]
  name = "Prof. Dr. Ulrich Dirnagl (Charite)"
  url = "mailto:ulrich.dirnagl@charite.de"

  [[members.contacts]]
  name = "Prof. Dr. Martin Reinhart (HU)"

  [[members.contacts]]
  name = "Prof. Dr. Beatrice Gründler (FU)"

  [[members.contacts]]
  name = "Prof. Dr. Manfred Hauswirth (TU)"
