[[resource]]
title = "UKRN Open Science Primers"
url = "https://www.ukrn.org/primers/"
image = "/resources/library/ukrn.png"
description = """The UK Reproducibility Network summarize many pertinent topics around Open Science in a [series of primers](https://www.ukrn.org/primers/)."""
footer = "Logo [CC-BY](https://www.ukrn.org/primers/)"
categories = [
  "Learning materials"
]

[[resource]]
title = "Open Scholarship Knowledge Base"
url = "https://www.cos.io/communities/open-scholarship-knowledge-base"
image = "/resources/library/oskb.png"
description = """In collaboration with the Center for Open Science, a worldwide community is gathering [resources concerning all aspects of Open Scholarship](https://www.cos.io/communities/open-scholarship-knowledge-base)."""
footer = "Logo [CC-BY](https://github.com/how-to-open-science/knowledge-base)"
categories = [
  "Learning materials"
]

[[resource]]
title = "FOSTER Open Science"
url = "https://www.fosteropenscience.eu/"
image = "/resources/library/foster.png"
image_padded = true
description = """FOSTER Open Science collects [training resources around Open Science](https://www.fosteropenscience.eu/) on an e-learning platform."""
footer = "Logo used [with permission](https://www.fosteropenscience.eu/about#logo)"
categories = [
  "Learning materials",
  "Training"
]

[[resource]]
title = "The Turing Way"
url = "https://the-turing-way.netlify.app"
image = "/resources/library/turing.jpg"
image_padded = true
description = """The Turing Way is an open source, community-driven [guide to reproducible, ethical, inclusive and collaborative data science](https://the-turing-way.netlify.app)."""
footer = "Logo [CC-BY](https://github.com/alan-turing-institute/the-turing-way/blob/master/LICENSE.md)"
categories = [
  "Learning materials"
]

[[resource]]
title = "Reproducibility for Everyone"
url = "https://repro4everyone.org"
image = "/resources/library/repro4everyone.png"
image_padded = true
description = """Repro4Everyone [develop resources and teach workshops that enable researchers to do reproducible research](https://repro4everyone.org). """
footer = "Logo [CC-BY](https://github.com/repro4everyone)"
categories = [
  "Training"
]

[[resource]]
title = "COS Ambassadors"
url = "https://www.cos.io/communities/ambassadors"
image = "/resources/library/cos.png"
image_padded = true
description = """COS Ambassadors are [local resources for increasing conversations around open science](https://www.cos.io/communities/ambassadors)."""
footer = "Logo [CC-0](https://osf.io/e7hrn/)"
categories = [
  "Community building"
]

[[resource]]
title = "INOSC Starter Kit"
url = "https://inosc-starter-kit.netlify.app/"
image = "https://inosc-starter-kit.netlify.app/media/image1.png"
image_padded = true
description = """The International Network of Open Science and Scholarship Communities provides an excellent starter kit for [founding and building a local Open Science community](https://inosc-starter-kit.netlify.app/)."""
footer = "Logo [CC-BY-NC-SA](https://github.com/aschetti/INOSC-starter-kit/)"
categories = [
  "Community building"
]

[[resource]]
title = "FORRT Educational Nexus"
url = "https://forrt.org/nexus/"
image = "/resources/library/forrt.svg"
description = """The FORRT initiative has collected and categorized [teaching and learning resources around open science](https://forrt.org/nexus/)."""
categories = [
  "Learning materials",
]

[[resource]]
title = "The Carpentries"
url = "https://carpentries.org/"
image = "/resources/library/carpentries.svg"
image_padded = true
description = """The Carpentries [teach foundational coding and data science skills](https://carpentries.org/) to researchers worldwide."""
footer = "Logo used [with permission](https://docs.carpentries.org/topic_folders/communications/resources/logos.html)"
categories = [
  "Training"
]

[[resource]]
title = "Center for Scientific Collaboration and Community Engagement"
url = "https://www.cscce.org/"
description = """The Center for Scientific Collaboration and Community Engagement (CSCCE) is a [research and training center to support and study the emerging field of scientific community engagement](https://www.cscce.org/)."""
categories = [
  "Community building"
]

[[resource]]
title = "Tilburg Science Hub"
url = "https://tilburgsciencehub.com"
image = "https://tilburgsciencehub.com/img/hero.svg"
description = """[Tilburg Science Hub](https://tilburgsciencehub.com) gives you the tools and guidance to be in control and save time in your empirical research projects."""
categories = [
  "Learning materials"
]
